.TH atualizador 1 "11 de Julho de 2024" "Versao 0.1.0" "Manual do Usuario"
.SH NOME
atualizador \- Atualiza o Sistema Integral da Avanco Informatica de forma automatizada

.SH SINOPSE
.B atualizador
[\fIOPÇÃO\fR]...
.SH DESCRIÇÃO
.B atualizador
é um script que executa a atualização de um programa em um servidor Linux.

.SH OPÇÕES
.TP
.B \-u, \--update
Atualiza o programa.
.TP
.B \-b, \--backup
Realiza backup antes da atualização.
.TP
.B \-a, \--auto-update
Atualiza este script para a versão mais recente.
.TP
.B \-h, \--help
Mostra esta mensagem de ajuda.

.SH EXEMPLOS
.B atualizador \--update
.br
Atualiza o programa.

.B atualizador \--backup
.br
Realiza backup antes da atualização.

.B atualizador \--auto-update
.br
Atualiza o script para a versão mais recente.

.SH AUTOR
Luiz Gustavo <luiz.gustavo@avancoinfo.com.br>

