#!/bin/bash
#
################################################################################
# atualizador - Programa para atualizar o sistema Integral
#
# DATA: 13/04/2024 11:27 - Versao 0.1.0
# -------------------------------------------------------------------------------
# Autor: Luiz Gustavo <luiz.gustavo@avancoinfo.com.br>
# -------------------------------------------------------------------------------
# Versao 0: Programa de atualizacao automatica.
# Versao 0.0.1: Logica do programa ajustada para gravar versao e release apos
#               execucao completa da atualizacao
# Versao 0.0.2: Logica para obter links de releases corrigidos
# Versao 0.0.3: Comandos rar sao exibidos com porcentagem em tela
# Versao 0.0.4: Criado teste para os arquivos baixados
# Versao 0.0.5: Criado teste para validar usuarios logados
# Versao 0.0.6: Validacao do Online, atraves do status-online.gnt
# Versao 0.0.7: Melhora na parte visual com porcentagens nos progressos
# Versao 0.0.8: Confirmacao de iniciar atualizacao, para evitar caso seja acio-
#               nado acidentamente.
# Versao 0.0.9: Desativado validacao de usuarios logados.
# Versao 0.0.10: Novos recursos e opcoes para linha de comando.
# Versao 0.1.0:  Diversas correcoes e melhorias.
#                Dentre elas melhor logica para obter os links atuais.
#
# -------------------------------------------------------------------------------
# Este programa ira atualizar o Sistema Integral respeitando a versao do cobol e
# instalando versao e a release mais recentes. Apos isso ira executar o atu-help
# manual e dar permissao em /u/sist/exec/*gnt.
# O objetivo desse Programa e facilitar o dia-a-dia do clinte usuario Avanco!
################################################################################
#


MANUAL_USO="
Programa: $(basename "$0")

--------------------------------------------------------------------------------
                              [OPCOES DISPONIVEIS]

OPCOES NA LINHA DE COMANDO:
    -h,  --help      Mostrar tela de ajuda.
    -V,  --version   Mostrar versao do Atualizador
    -b,  --baixar    Baixar atualizacoes do Integral
    -up, --update    Realizar update do Atualizador
    -m,  --menu      Menu interativo

MODO DE USAR:
Digite o nome do programa e a opcao desejada.
  Exemplo:
  atualizador --help
  'Exibir tela de ajuda.'

--------------------------------------------------------------------------------

  Usando o programa de atualizacao automatica:
    Na primeira utilizacao e necessario usar o configurarAtualizador.sh
     -Modo de uso:
        Baixe os seguintes arquivos no servidor da Avanco:
        (Eles se encontram em '/u/rede/avanco/pacoteAtualizador')
         - configurarAtualizador.sh
         - atualizador.rar
        Apos baixar na sua maquina, coloque os arquivos no diretorio do servi-
        dor do cliente:
         - '/u/rede/avanco/'
        Apos colocar os arquivos no local correto e entrar como root, digite:
         -> bash /u/rede/avanco/configurarAtualizador.sh
        Basta apertar enter, e sera realizada a configuracao dos scripts nos
        locais corretos.
        Em seguida logue como usuario 'avanco'
         -> su - avanco
         
    Apos a configuracao feita, digite o comando 'atualizador' no terminal e
    pressionar Enter.

    Para iniciar a atualizacao e necessario confirmar pressionando o 'S'.
    Para sair, pressione 'N'.

    Ao utilizar o 'Atualizador' pela primeira vez ele exibira a seguinte mensa-
    gem:
      'O arquivo com as informacoes de versao e release nao existe'.
     - Informe a VERSAO ATUAL do Integral: (DDMMAA)

    Nesse momento sera necessario informar a versao e release que se encontram
    no servidor do cliente.
    Informar a data somente com numeros conforme exemplo abaixo.
     ex.: 090424

    Apertar Enter.
    Informe a RELEASE ATUAL do Integral (se nao existir deixe em branco):
     ex.: e
    Apertar Enter
    
    Sera exibido essa tela:
      VERSAO COBOL: 4.0
      VERSAO INTEGRAL: 090424
      RELEASE INTEGRAL: E
      Confirma as informacoes fornecidas? (S/N)

    Caso as informacoes estiverem corretas basta apertar 'S' para prosseguir,
    caso contrario pressione 'N'. Sera necessario reiniciar o processo.
    

    O atualizador conta com recursos extras atraves do menu.
    Para acessar o menu digite na linha de comando:
        -> 'atualizador --menu' ou 'atualizador -m' e aperte Enter.

    Ao entrar no menu de recursos extras, aparecera a seguinte tela:
   ___________________________________________________________________________
  |                                                                           |
  |  1) OBTER INFORMACOES DO SISTEMA         5) CONFIGURAR ROTINA NO CRON     |
  |  2) ATUALIZAR                            6) OBTER UPDATE DO ATUALIZADOR   |
  |  3) RESTAURAR ATUALIZACAO ANTERIOR       7) MANUAL                        |
  |  4) CORRIGIR FALHAS DE ATUALIZACAO       99) SAIR                         |
  |___________________________________________________________________________|

    Escolha uma OPCAO:

    Escolha a opcao desejada de acordo com os numeros exibidos acima.

        1) OBTER INFORMACOES DO SISTEMA
            Exibira na tela os detalhes da ultima atualizacao executada.

        2) ATUALIZAR
            Atualizara o sistema Integral
        
        3) RESTAURAR ATUALIZACAO ANTERIOR
            Essa opcao so e recomendada caso alguma rotina nao estiver funcio-
            nando como estava. Porem, antes de realiza-la acione o suporte
            Avanco para que um tecnico registre a demanda e encaminhe para os
            desenvolvedores.

        3.a) Dentro da opcao 'RESTAURAR ATUALIZACAO ANTERIOR' aparecera o menu:


        4) CORRIGIR FALHAS DE ATUALIZACAO
            Essa opcao ira exibir possiveis falhas na hora de atualizar.
            Consulte o topico de ajuda apertando 4, no menu.
        
        5) CONFIGURAR ROTINA NO CRON
            Essa opcao devera ser executada somente pelo suporte Avanco.
            Caso deseje que o Integral seja atualizado automaticamente durante
            a madrugada acione o suporte Avanco para deixar essa opcao ativa.

        6) OBTER UPDATE DO ATUALIZADOR
            Executar essa opcao caso apareca alguma mensagem de erro ou falha
            no terminal ao tentar atualizar.

            Se voce executou o update do Atualizador e mesmo assim nao conseguiu
            atualizar, veja o menu 4, caso o problema persista favor acionar o
            Suporte Avanco.
        
        7) MANUAL
            Sera exibido esse menu de ajuda.
        
        99) SAIR
            Para sair do menu de interacao.
        

    # Programa de Atualizacao Automatica
    #
    # Este programa e responsavel por executar automaticamente o processo de
    # atualizacao do sistema.
    # Ao ser executado, o programa realizara as seguintes acoes:
    #   1. Verificar o Online e desativa-lo durante a atualizacao.
           Apos finalizar ativa-lo novamente.
    #   2. Obter as atualizacoes mais recentes do Integral.
    #   3. Ler versao e release informada pelo usuario e gravar para as proximas
    #      atualizacoes, sendo necessario realizar esta acao apenas uma vez.
    #   4. Realiza o backup respeitando os padroes da Avanco.
    #   5. Descompactar os pacotes baixados no local correto e conceder as per-
    #      missoes aos '.gnt'
--------------------------------------------------------------------------------
    #
    # OBSERVACAO: SERA GERADO UM ARQUIVO DE LOG PARA CONSULTA! ELE CONTERA AS
    # INFORMACOES DE:
    #                 - DATA DA ATUALIZACAO
    #                 - BACKUP VERIFICADO
    #                 - VERSAO DO COBOL
    #                 - VERSAO INTEGRAL ANTES DA ATUALIZACAO
    #                 - RELEASE INTEGRAL ANTES DA ATUALIZACAO
    #                 - VERSAO INTEGRAL INSTALADA
    #                 - RELEASE INTEGRAL INSTALADA
    #                 - DATA E HORA DO BACKUP
--------------------------------------------------------------------------------
    # Observacoes:
    #   - Caso tenha alguma intercorrencia ou tenha alguma sugestao de melhoria,
      contactar no e-mail: luiz.gustavo@avancoinfo.com.br
--------------------------------------------------------------------------------
"

GUIA_ERROS="
    Elaborar ainda.
"

AVANCO="
                                                          ##                    
                                                        ####                    
                                                      ######                    
                                                    ########                    
                        ------------              ##########                    
                      ------                    ############                    
                    ------                    ##############                    
                      ----                  ################                    
                      ----                ########  ########                    
                        ----            ########    ########                    
                          ----       #########      ########                    
                            --    ########          ########                    
                              --########            ########                    
                              ##----                  ######                    
                            ######----                ######                    
                          ####        ----            ######                    
                        ####              --                                    
                      ####                    --                                
                    ##                            --                            
                  ##                                    --                      
                                                                                
                                                                                
                                                                                
    ##         ##  ##         ##         ##    ##        #####        #####
  ##  ##       ##  ##       ##  ##       ####  ##       ##          ##    ##
  ##  ##       ##  ##       ##  ##       ##  ####       ##          ##    ##
  ##  ##         ##         ##  ##       ##    ##        #####       #####
"


###############################
# -------------------------------------------------------------------------------
# Criando opcoes visuais
# Cores
readonly RED='\e[1;91m'
readonly GREEN='\e[1;92m'
readonly YELLOW='\e[1;93m'
readonly BLUE='\e[1;94m'
readonly MAGENTA='\e[1;95m'
readonly CYAN='\e[1;96m'
readonly NO_COLOR='\e[0m'

# Variaveis globais
info_loja_txt="/u/sist/controle/info_loja.txt"



dia_semana_lido=$(date +%u)
hora_lida=$(date +%H)
CONTAUSER=$(ps ax | grep rts32 | grep -v 'grep' | wc -l)
status_ON=$(cobrun status-online.gnt "L") > /dev/null 2>&1

# datas
MES_ANO=$(date +"%m%y")
MES_ATUAL=$(date +"%m")
ANO_ATUAL=$(date +"%y")

DATE=$(date +"%d%m%y")

MES_ANTERIOR=$(date -d "4 weeks ago" +"%m")
ANO_ANTERIOR=$(date -d "4 weeks ago" +"%y")

# Locais dentro do sevidor
LOCAL_GNT="/u/sist/exec"
PASTA_AVANCO="/u/rede/avanco"
REMOVIDOS="$PASTA_AVANCO/removidos"
PASTA_DESTINO="/u/rede/avanco/atualizacoes"

arquivo_versao_atual=""
arquivo_release_atual=""

LOCAL_LOG="/u/sist/logs"            # arquivo de log
BKP_DESTINO="/u/sist/exec-a"
BKP_TOTAL="BKPTOTAL_$DATE.rar" # local de onde serao salvos os backups
BKP_RELEASE="BKPRELEASE_$DATE.rar" # local de onde serao salvos os backups


# Arquivos de log para consulta.
TESTE_GNT_LOG="/u/sist/logs/testeGNT.log"
VALIDADOS_GNT="/u/sist/logs/statusGNT.log"

infos_extras="/u/sist/logs/infos_extras.log"

# Arquivo de log
LOG_FILE="/u/sist/logs/log_$MES_ANO.log"
# Arquivo de log de erro
ERRO_LOG_FILE="/u/sist/logs/erro_$MES_ANO.log"

# arquivo de pre leitura
controle_servidor="/u/sist/controle"

script_baixar_atualizacao="/u/bats/baixarAtualizacao"


# Parte web - Links

SCRIPT_URL="https://raw.githubusercontent.com/ketteiGustavo/atualizador/main/Atual/atualizador"
SCRIPT_PATH="$0"
URL_CONTROLE_VERSAO_RELEASE="https://raw.githubusercontent.com/ketteiGustavo/atualizador/main/Atual/controle_ver_rel.txt"



versaoCobol=""    # usada para armazenar o cobol, apos rodar cobrun integral


# trabalhando as variaveis que receberao datas que sao baseada em datas
novoPortal=""       # responsavel por obter a atual versao no site e ser usada para comparacoes
novoPortalPosRelease=""
releasePortal=""    # armazenara a data da release (precisa validar, pois nao havia release disponivel no dia do teste)
letraRelease=""     # cada release e unica, tem uma letra propria, aqui ficara essa informacao
versaoLoja=""       # usada para obter a versao no servidor do cliente
releaseLoja=""      # usada para obter a release no servidor do cliente
inf_versao=""
inf_release=""      # usada para obter a release digitada

inf_versaoCobol=""
inf_versaoLoja=""
inf_releaseLoja=""
dia=""
mes=""
ano=""
data_release_servidor=""
data_release_baixar=""
data_release=""
cronometro_start=$(date +'%H:%M:%S')
cronometro_start_volta=""
cronometro_stop=""
cronometro_stop_volta=""
tempo_gasto=""
atualizado_flag=""
controle_flag="/u/sist/controle"
flag_versao=false
flag_release=false



RESULTADO=""        # armazena a saida do comando cobrun, para separar somente a versao 4.0 ou 4.1

DATA_ATUAL=$(date +"%d%m%y")       # data obtida ao rodar o script, sera sempre o dia atual
HORA_ATUAL=$(date +"%H:%M:%S")     # hora para gravacoes necessarias
DIA_HOJE=$(date +"%Y%m%d")



################################################################################

# Funcao para exibir mensagens de erro em vermelho
ERRO_MSG() {
    echo -e "${RED}[ERROR] - $1${NO_COLOR}"
}

# Funcao para exibir mensagens de informacao em verde
INFO_MSG() {
    echo -e "${GREEN}[INFO] - $1${NO_COLOR}"
}

# Funcao para exibir mensagens de alerta em amarelo
ALERTA_MSG() {
    echo -e "${YELLOW}[ALERTA] - $1${NO_COLOR}"
}

# Funcao para exibir mensagens em azul
BLUE_MSG() {
    echo -e "${BLUE} $1${NO_COLOR}"
}

# Funcao para exibir mensagens em magenta
MAGENTA_MSG() {
    echo -e "${MAGENTA} $1${NO_COLOR}"
}

# Funcao para exibir mensagens em ciano
CYAN_MSG() {
    echo -e "${CYAN} $1${NO_COLOR}"
}

# ------------------------------------------------------------------------------


INICIAR () {
    while true; do
        read -p "Dejesa iniciar a atualizacao? (S/N) " confirma_inicio

        case $confirma_inicio in
            "S" | "s" )
                echo "Atualizador Integral"
		clear
                break
                ;;
            "N" | "n")
		clear
                tput smso
                echo "                                AVANCO INFORMATICA                              "
                echo ""
                echo "                            TELESUPORTE (31) 3025-1188                          "
                echo ""
                echo "                                    TELEGRAM                                    "
                echo ""
                echo "                            t.me/avancoinformatica_bot                          "
                tput rmso
                stty sane
                exit 0
                ;;
            *)
                echo "Entrada invalida, confirme com (S) para sim ou (N) para nao"
                ;;
        esac
    done
}




# funcao para verificar se o sistema foi atualizado no dia
VERIFICA_ATUALIZACAO () {
    if [ -f "$info_loja_txt" ]; then
        ultima_atu=$(grep "DATA: " "$info_loja_txt" | cut -d ' ' -f 2)
        if [ "$ultima_atu" == "$(date +'%d/%m/%Y')" ]; then
            
            clear
            tput smso
            echo "                  O INTEGRAL JA FOI ATUALIZADO HOJE $(date +'%d/%m/%Y')         "
            echo ""
            echo "                                AVANCO INFORMATICA                              "
            echo ""
            echo "                            TELESUPORTE (31) 3025-1188                          "
            echo ""
            echo "                                    TELEGRAM                                    "
            echo ""
            echo "                            t.me/avancoinformatica_bot                          "
            tput rmso
            stty sane
            sleep 2

        exit 0
	else
        echo "Atualizando..." > /dev/null
        cronometro_start_volta=$SECONDS
        fi
    fi
}


VERIFICA_ONLINE () {
        if [ $CONTAUSER != 0 ]; then
            ALERTA_MSG "Existem usuarios logados no INTEGRAL! Por favor peca para deslogarem do sistema para a atualizacao!"
            echo "USUARIOS LOGADOS"
            w -shu
            exit 0
        fi
}
# Funcao para verificar o dia da semana e hora
verificar_dia () {
    if [ $dia_semana_lido -eq 5 ] || [ $dia_semana_lido -eq 6 ] || [ $dia_semana_lido -eq 7 ]; then
        clear
        tput smso
        echo "  O sistema nao pode ser atualizado hoje! Tente novamente na 'Segunda-Feira'!   "
        echo ""
        echo "                                AVANCO INFORMATICA                              "
        echo ""
        echo "                            TELESUPORTE (31) 3025-1188                          "
        echo ""
        echo "                                    TELEGRAM                                    "
        echo ""
        echo "                            t.me/avancoinformatica_bot                          "
        tput rmso
        stty sane
        exit 0
    fi

    if [ $dia_semana_lido -eq 2 ] && [ $hora_lida -ge 6 ] && [ $hora_lida -lt 15 ]; then
        clear
        tput smso
        echo "                           Favor atualizar apos as 16h!                         "
        echo ""
        echo "                                AVANCO INFORMATICA                              "
        echo ""
        echo "                            TELESUPORTE (31) 3025-1188                          "
        echo ""
        echo "                                    TELEGRAM                                    "
        echo ""
        echo "                            t.me/avancoinformatica_bot                          "
        tput rmso
        stty sane
        exit 0
    fi

    if [ $hora_lida -gt 18 ]; then
        clear
        tput smso
        echo "               FAVOR EXECUTAR A ATUALIZACAO EM HORARIO COMERCIAL!               "
        echo ""
        echo "                               AVANCO INFORMATICA                               "
        echo ""
        echo "                           TELESUPORTE (31) 3025-1188                           "
        echo ""
        echo "                                    TELEGRAM                                    "
        echo ""
        echo "                            t.me/avancoinformatica_bot                          "
        tput rmso
        stty sane
        exit 0
    fi

    if [ $dia_semana_lido -eq 4 ] && [ $hora_lida -ge 17 ]; then
        clear
        tput smso
        echo "         Recomendamos atualizar na 'Segunda-Feira', devido ao horario!          "
        echo ""
        echo "                           Bom tarde e bom fim de semana                        "
        echo ""
        echo "                                AVANCO INFORMATICA                              "
        echo ""
        echo "                            TELESUPORTE (31) 3025-1188                          "
        echo ""
        echo "                                    TELEGRAM                                    "
        echo ""
        echo "                            t.me/avancoinformatica_bot                          "
        tput rmso
        stty sane
        exit 0
    fi
    sleep 3
}

if [ "$status_ON" = "ATIVADO" ]; then
    status_ON=$(cobrun status-online.gnt "D") > /dev/null
fi

# Criando diretorio de logs e atualizacoes
if [ ! -d "/u/rede/avanco/atualizacoes" ]; then
    mkdir -p "/u/rede/avanco/atualizacoes"
    chmod 777 -R "/u/rede/avanco/atualizacoes"
fi

# Criando diretorio de logs e atualizacoes
if [ ! -d "$REMOVIDOS" ]; then
    mkdir -p "$REMOVIDOS"
    chmod 777 -R "$REMOVIDOS"
fi


if [ ! -d "/u/sist/controle" ]; then
    mkdir -p "/u/sist/controle"
    chmod 766 -R "/u/sist/controle"
fi

if [ ! -d "/u/sist/logs" ]; then
    mkdir -p "/u/sist/logs"
    chmod 766 -R "/u/sist/logs"
fi

if [ ! -f "/u/sist/logs/log-de-remocao.log" ]; then
    echo "               Controle de Backups Removidos" > /u/sist/logs/log-de-remocao.log
    echo "      DATA        -    HORA   -             DIRETORIO" >> /u/sist/logs/log-de-remocao.log
fi


if [ ! -f "/u/sist/logs/infos_extras.log" ]; then
    echo "Controle de Desempenho do Atualizador no servidor" > "/u/sist/logs/infos_extras.log"
    echo "DIA DA ATUALIZACAO  -    HORA INICIAL    -    HORA FINAL     -    TEMPO GASTO" >> "/u/sist/logs/infos_extras.log"
fi


rm -rf /u/rede/avanco/atualizacoes/versao*
rm -rf /u/rede/avanco/atualizacoes/release*

# Funcao para verificar permissao e grupo dos programas .gnt
SEGURANCA(){
    sleep 3
    if [ -f "$TESTE_GNT_LOG" ] && [ "$(date -r "$TESTE_GNT_LOG" +%Y%m%d)" = "$DIA_HOJE" ]; then
        mapfile -t gnt_files < "$TESTE_GNT_LOG"
    else
        gnt_files=($(find "$LOCAL_GNT" -name "*.gnt"))
    fi

    if [ ${#gnt_files[@]} -eq 0 ]; then
        echo "Nenhum arquivo '.gnt' encontrado no diretorio '$LOCAL_GNT'."
        exit 1
    fi

    all_valide=true
    total_files_teste=${#gnt_files[@]}
    contagem_gnt=0

    > "$TESTE_GNT_LOG"

    for file in "${gnt_files[@]}"; do
        clear
        contagem_gnt=$((contagem_gnt + 1))
        porc_gnt=$((contagem_gnt * 100 / total_files_teste))
        echo "validando os programas... ($porc_gnt%)"
        permissions=$(stat -c "%a" "$file")
        if [ "$permissions" -ne 777 ]; then
            ALERTA_MSG "O programa $file nao tem permissao total!"
            echo "O programa $file nao tem permissao total!" >> $VALIDADOS_GNT
            echo "Favor acionar o suporte Avanco!"
            all_valide=false
            echo "$file" >> "$TESTE_GNT_LOG"
        fi

        dono=$(stat -c "%U %G" "$file")

        if [ "$dono" != "avanco sist" ]; then
            ALERTA_MSG "O programa $file nao esta com o usuario: avanco e o grupo: sist."
            echo "O programa $file nao esta com o usuario: avanco e o grupo: sist." >> $VALIDADOS_GNT
            ALERTA_MSG "Favor acionar o suporte Avanco!"
            all_valide=false
            echo "$file" >> "$TESTE_GNT_LOG"
        fi
    done

    if [ "$all_valide" = true ]; then
        INFO_MSG "Iniciando a atualizacao automatica!"
        rm -f "$TESTE_GNT_LOG"
	    rm -f "$VALIDADOS_GNT"
    else
        ALERTA_MSG "E necessario acionar o suporte Avanco para executar as permissoes"
        sleep 1
	exit 1
    fi
}


# Funcao para testar e verificar sinal e qualidade da internet
checar_internet () {
    # Endereço para pingar (Google DNS)
    local host="8.8.8.8"
    
    # Pingar o endereço 4 vezes e capturar a saída
    ping_output=$(ping -c 4 $host)
    ping_exit_status=$?

    # Verificar se o comando ping teve sucesso
    if [ $ping_exit_status -eq 0 ]; then
        # Extrair os tempos de resposta
        rtt_min=$(echo "$ping_output" | grep "rtt" | awk -F'/' '{print $4}')
        rtt_avg=$(echo "$ping_output" | grep "rtt" | awk -F'/' '{print $5}')
        rtt_max=$(echo "$ping_output" | grep "rtt" | awk -F'/' '{print $6}')
        
        echo "CONEXAO COM A INTERNET OK"
        #echo "TEMPO DE RESPOSTA (ms):"
        #echo "MINIMO: $rtt_min"
        #echo "MEDIO: $rtt_avg"
        #echo "MAXIMO: $rtt_max"

        # Verificar se a conexão está lenta ou instável
        if (( $(echo "$rtt_avg > 100" | bc -l) )); then
            echo "AVISO: A CONEXAO ESTA LENTA"
        fi
        if (( $(echo "$rtt_max - $rtt_min > 100" | bc -l) )); then
            echo "AVISO: A CONEXAO ESTA INSTAVEL"
        fi
    else
        # Mensagem de erro centralizada
        clear
        tput cup $(($(tput lines)/2)) $(($(tput cols)/2-20))
        echo "NAO HA CONEXAO COM A INTERNET"
        exit 1
    fi
}


# funcao para validar data
validar_data() {
    data_verificada=$(date -d "$1" +"%d%m%y" 2>/dev/null)
    if [ $? -eq 0 ]; then
        return 0
    else
        return 1
    fi
}



# Funcao para criar o arquivo 'info_loja.txt'
CRIAR_INFO_LOJA() {
    data_configuracao=$(date +'%d/%m/%Y')

    VERIFICA_COBOL
    # loop para validar versao
        while true; do
            read -p "Informe a VERSAO ATUAL do Integral: (DDMMAA) " inf_versaoLoja
            if validar_data "$inf_versaoLoja"; then
                if [[ ! "$inf_versaoLoja" =~ ^[0-9]{6}$ ]]; then
                    ERRO_MSG "Versao informada invalida! Por favor, digite novamente (DDMMAA)"
                else
                    break
                fi
                break
            else
                ERRO_MSG "Versao informada invalida! Por favor, digite novamente (DDMMAA)"
            fi
        done

        # loop para validar release
        while true; do
            read -p "Informe a RELEASE ATUAL do Integral (se nao existir deixe em branco): " inf_releaseLoja
            inf_releaseLoja=$(echo "$inf_releaseLoja" | tr '[:lower:]' '[:upper:]')
            if [[ ! "$inf_releaseLoja" =~ ^[A-Z]$ ]] && [ ! -z "$inf_releaseLoja" ]; then
                ERRO_MSG "Release invalida. A release deve conter e ser apenas uma letra ou vazia se nao existir!"
            else
                break
            fi
        done
        
        while true; do
            echo
            echo "VERSAO COBOL: $inf_versaoCobol"
            echo "VERSAO INTEGRAL: $inf_versaoLoja"
            echo "RELEASE INTEGRAL: $inf_releaseLoja"
            read -p "Confirma as informacoes fornecidas? (S/N) " confirmar_infos

            case $confirmar_infos in
                "S" | "s")
                    echo "Informacoes validadas"
                    break
                    ;;
                "N" | "n")
                    echo "Saindo"
                    exit 0
                    ;;
                *)
                    echo "Entrada invalida, confirme com (S) para sim ou (N) para nao"
                    ;;
            esac
        done
    
    echo
    echo "Gravando informacoes. Por favor, aguarde..."
        
    echo "DATA: $data_configuracao" > "$info_loja_txt"
    echo "VERSAO COBOL: $inf_versaoCobol" >> "$info_loja_txt"
    echo "VERSAO INTEGRAL: $inf_versaoLoja" >> "$info_loja_txt"
    echo "RELEASE: $inf_releaseLoja" >> "$info_loja_txt"
    echo "DATA RELEASE: " >> "$info_loja_txt"
    echo "$inf_versaoLoja" > "/u/sist/controle/inf_versaoLoja.txt"
    echo "$inf_releaseLoja" > "/u/sist/controle/inf_releaseLoja.txt"
}

# Funcao para ler o arquivo 'info_loja_txt'
LER_ARQUIVO_TEXTO() {
    VERIFICA_COBOL
    local arquivo="$info_loja_txt"

    # verifica se o arquivo existe
    if [ ! -f "$arquivo" ]; then
        echo "O arquivo com as informacoes de versao e release nao existe." 2> >(tee -a "$ERRO_LOG_FILE")
        CRIAR_INFO_LOJA
        return 1
    fi

    # Le o arquivo linha por linha e armazena o conteudo em variaveis
    while IFS= read -r linha; do
        # verifica se a linha nao esta vazia
        if [ -n "$linha" ]; then
            # divide a linha em partes usando ":" como delimitador
            chave=$(echo "$linha" | awk -F': ' '{print $1}')
            valor=$(echo "$linha" | awk -F': ' '{print $2}')

            # Armazenando a chave e o valor em variaveis
            case "$chave" in
                "DATA")
                    inf_data="$valor"
                    echo
                    echo "Data da ultima atualizacao executada: $inf_data"
                    ;;
                "VERSAO COBOL")
                    inf_versaoCobol="$valor"
                    echo "$inf_versaoCobol"
                ;;
                "VERSAO INTEGRAL")
                    inf_versaoLoja="$valor"
                    inf_versao="$valor"
                    echo "Versao atual no Servidor: $inf_versaoLoja"
                    echo "$inf_versaoLoja" > "/u/sist/controle/inf_versaoLoja.txt"
                ;;
                "RELEASE")
                    inf_releaseLoja="$valor"
                    inf_release="$valor"
                    echo "Release atual no Servidor: $inf_releaseLoja"
                    echo "$inf_releaseLoja" > "/u/sist/controle/inf_releaseLoja.txt"
                    echo
                ;;
                "DATA RELEASE")
                    data_release_servidor="$valor"
                    echo "Data da release no Servidor: $data_release_servidor"
                    echo
                ;;
                *) echo "Chave desconhecida: "
                ;;
            esac
        fi
    done < "$arquivo"
}


# Funcao para verificar qual o cobol usado
VERIFICA_COBOL() {
    # Rebece as informacoes a funcao LER_ARQUIVO_TEXTO
    RESULTADO=$(cobrun 2>&1)
    if [[ $RESULTADO =~ V([0-9]+\.[0-9]+) ]]; then
        versaoCobol="${BASH_REMATCH[1]}"
        echo "Versao do Cobol: $versaoCobol" > /dev/null
        inf_versaoCobol="$versaoCobol"
    fi
    #versaoCobol="4.0"
    #inf_versaoCobol="$versaoCobol"
}

# Funcao para limpar qualquer arquivo ou pasta que esteja errado no sist/exec
LIMPA_EXEC () {
    local data_clear=$(date +'%d/%m/%Y')
    local rar_file="$REMOVIDOS/removidos_$DATA_ATUAL.rar"
    echo "Arquivos e Pastas que estavam no 'u/sist/exec' no dia $data_clear" > "/u/sist/logs/removidos_$DATA_ATUAL.log"
    for item in "$LOCAL_GNT"/*; do
        # valida se e um programa gnt
        if [[ ! "$item" =~ \.gnt$ ]]; then
            echo "Arquivo/Pasta encontrado -> $item" >> "/u/sist/logs/removidos_$DATA_ATUAL.log"

            # compactando arquivo encontrado
            rar a "$rar_file" "$item"

            rm -rf "$item"
        fi
    done
}

# -----------------------------------------------------------------------------
# Funcoes de log

# Funcao para controlar registro de logs
MANTER_LOG_ATUAL() {

    log_atual=$ANO_ATUAL$MES_ATUAL
    log_anterior=$ANO_ANTERIOR$MES_ANTERIOR
    log_remover=$MES_ANTERIOR$ANO_ANTERIOR


    if [ ! -e "$LOCAL_LOG/log_$MES_ANO.log" ]; then
        touch "$LOCAL_LOG/log_$MES_ANO.log"
    fi

    if [ "$log_atual" != "$log_anterior" ]; then
        if [ -e "$LOCAL_LOG/log_$log_remover.log" ]; then
            rm "$LOCAL_LOG/log_$log_remover.log"
        fi
    fi

    for arquivo in "$LOCAL_LOG"/log_*.log; do
        if [ "$arquivo" != "$LOCAL_LOG/log_$MES_ANO.log" ] && [ "$arquivo" != "$LOCAL_LOG/log_erro_$MES_ANO.log" ]; then
            rm "$arquivo"
        fi
    done

    #echo "$(date +'%d/%m/%Y - %H:%M:%S')" >> "$LOCAL_LOG/log_$MES_ANO.log"
    echo "" >> "$LOCAL_LOG/log_$MES_ANO.log"
}


MANTER_LOG_ERRO_ATUAL() {
    log_erro_atual=$ANO_ATUAL$MES_ATUAL
    log_erro_anterior=$ANO_ANTERIOR$MES_ANTERIOR
    log_erro_remover=$MES_ANTERIOR$ANO_ANTERIOR


    if [ ! -e "$LOCAL_LOG/erro_$MES_ANO.log" ]; then
        touch "$LOCAL_LOG/erro_$MES_ANO.log"
    fi

    if [ "$log_erro_atual" != "$log_erro_anterior" ]; then
        if [ -e "$LOCAL_LOG/erro_$log_erro_remover.log" ]; then
            rm "$LOCAL_LOG/erro_$log_erro_remover.log"
        fi
    fi

    #echo "$(date +'%d/%m/%Y - %H:%M:%S')" >> "$LOCAL_LOG/erro_$MES_ANO.log"
    echo "" >> "$LOCAL_LOG/erro_$MES_ANO.log"
}

# Funcao para criar e ou atualizar o arquivo de log com as informacoes padroes
LOG_INFO() {
    MANTER_LOG_ATUAL
    local info="$1"
    local log_msg="\n################################################################################\n[$(date '+%d/%m/%Y %H:%M:%S')] \n- $info \n- VERSAO COBOL: $versaoCobol \n- VERSAO INTEGRAL ANTES: $inf_versaoLoja \n- RELEASE INTEGRAL ANTES: $inf_releaseLoja \n- VERSAO INSTALADA: $novoPortal \n- RELEASE INSTALADA: $data_release - $letraRelease \n- BACKUP realizado no dia $(date +"%d/%m/%Y") as $(date +"%H:%M:%S") no $BKP_DESTINO/BKPTOTAL_$DATE\n################################################################################"

    # Escreve no arquivo de log
    echo -e "$log_msg\n" >> "$LOG_FILE"

    # Verifica se o arquivo foi criado com sucesso
    if [ $? -ne 0 ]; then
        echo "Erro ao escrever no arquivo de log." >&2
        exit 1
    fi
}

# Funcao para criar e ou atualizar o arquivo de logERRO com as informacoes padroes
LOG_ERROR() {
    MANTER_LOG_ERRO_ATUAL
    local error="$1"
    echo "$(date '+%d/%m/%Y %H:%M:%S') - $error" >> "$ERRO_LOG_FILE"
}


# ------------------------------------------------------------------------------

# Funcao para converter datas no formato YYYYMMDD, para ser usado em equacoes de comparacao, maior, menor e igual
CONVERTER_DATAS() {
    local dia="${1:0:2}"
    local mes="${1:2:2}"
    local ano="${1:4:2}"
    # Convertendo para o formato 'YYYYMMDD' para facilitar a adição de dias
    local data_formatada="20${ano}${mes}${dia}"
    echo "$data_formatada"
    
}

# Funcao para tratar datas e inserir barras entre os digitos deixando DD/MM/AA
TRATAR_DATAS () {
    local dia_td=${1:0:2}
    local mes_td=${1:2:2}
    local ano_td=${1:4:2}
    local data_tratada="${dia_td}/${mes_td}/${ano_td}"
    echo "$data_tratada"
}



# Funcao para chamar o script que realiza o download
BAIXAR_ATUALIZACOES () {
    echo ""
    bash "$script_baixar_atualizacao"
    if [ -f "/u/sist/controle/versaoIntegral" ] && [ -s "/u/sist/controle/versaoIntegral" ]; then
        novoPortal=$(cat "/u/sist/controle/versaoIntegral")
    fi
    if [ -f "/u/sist/controle/releaseIntegral" ] && [ -s "/u/sist/controle/releaseIntegral" ]; then
        letraRelease=$(cat "/u/sist/controle/releaseIntegral")
    else
        letraRelease=""
    fi
}

# Funcao para realizar backup
FAZER_BKP() {
    # Caminho completo para o destino do backup

    if [ -e "$BKP_DESTINO/BKPTOTAL_$DATE.rar" ]; then
        # se o backup existir com a data atual permite atualizar
        sleep 1
        return 0
    else
        ALERTA_MSG "Realizando backup dos programas..."
        total_bkp_files=$(find $LOCAL_GNT -type f -name "*.gnt" | wc -l)
        contagem_arquivo=0
        # Verifica se o comando anterior foi executado com sucesso
        if rar a "$BKP_DESTINO/BKPTOTAL_$DATE" $LOCAL_GNT/*gnt | while read -r line; do
            ((contagem_arquivo++))
            porcentagem_bkp=$((contagem_arquivo *100 / total_bkp_files))
            echo -ne "Criando Backup: [$porcentagem_bkp%]\r"
        done
        then
            INFO_MSG "Backup concluido!"
        else
            ERRO_MSG "Erro ao realizar Backup em $DATE!"
            LOG_ERROR "Erro ao relizar Backup em $DATE"
        fi
    fi

    find /u/sist/exec-a/ -name "BKPTOTAL_*" -type f -printf '%T@ %p\n' | sort -n | head -n -4 | cut -d' ' -f2- | while read file; do echo "No dia $(date +'%d/%m/%Y as %H:%M:%S') - o backup foi removido de: $file" >> /u/sist/logs/log-de-remocao.log; rm -f "$file"; done

}

# Funcao para verificar se o backup foi feito no dia atual
VERIFICA_BACKUP() {

    if [ -e "$BKP_DESTINO/BKPTOTAL_$DATE.rar" ]; then
        # se o backup existir com a data atual permite atualizar
        INFO_MSG "Backup verificado!"
        return 0
    else
        # se o backup nao existir, alertar ao usuario e voltar ao menu principal
        ALERTA_MSG "POR FAVOR FACA O BACKUP ANTES DE ATUALIZAR"
        echo "Arquio de BACKUP nao foi localizado! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
        sleep 1
        return 1
    fi
}

definirPacote_por_cobol () {
    
    cobolBusca=""
    versaoBusca=$(cat "/u/sist/controle/versaoIntegral")
    data_release=$(cat "/u/sist/controle/dataReleaseIntegral")


    local ver="${versaoBusca:0:4}"
    local rel="${data_release:0:4}"
    

    # Define o diretorio com base na versao do Cobol
    if [ "$versaoCobol" == "4.0" ]; then
        cobolBusca="40"
        arquivo_versao_atual=$(find "$PASTA_DESTINO" -type f -name "versao$cobolBusca-$versaoBusca.rar")
        arquivo_release_atual=$(find "$PASTA_DESTINO" -type f -name "release$cobolBusca-$ver-a-$rel.rar")
	sleep 1
    elif [ "$versaoCobol" == "4.1" ]; then
        cobolBusca="41"
        arquivo_versao_atual=$(find "$PASTA_DESTINO" -type f -name "versao$cobolBusca-$versaoBusca.rar")
        arquivo_release_atual=$(find "$PASTA_DESTINO" -type f -name "release$cobolBusca-$ver-a-$rel.rar")
    sleep 1
    else
        ERRO_MSG "Versao do Cobol desconhecida: $versaoCobol"
        echo "Versao do Cobol desconhecida: $versaoCobol" >> $ERRO_LOG_FILE
        exit 1
    fi
}

# Funcao para atualizar o sistema
ATUALIZAR() {
    BAIXAR_ATUALIZACOES
    definirPacote_por_cobol
    #echo "Pacote da versao: $arquivo_versao_atual"
    #echo "Pacote da release: $arquivo_release_atual"
    local DIRCERTO="/u/sist/exec"
    
    if [ ! -d "$DIRCERTO" ]; then
        ERRO_MSG "O diretorio nao existe."
        echo "O diretorio nao existe." >> $ERRO_LOG_FILE
        exit 1
    fi

    cd "$DIRCERTO"
    atualizado_flag=$(cat "$controle_flag/controle_flag.txt")
    if [ -z "$atualizado_flag" ]; then
        echo "STATUS NAO ENCONTRADO"
        exit 1
    fi

    if [ "$atualizado_flag" != "true" ]; then
        FAZER_BKP
        VERIFICA_BACKUP
    fi

    echo "Loja: versao - $inf_versaoLoja - release - $inf_releaseLoja"
    echo "Portal: versao - $novoPortal - release - $letraRelease"

    # Verifica se a versão está desatualizada
    if [ "$inf_versaoLoja" != "$novoPortal" ]; then
        # Verifica se o arquivo de atualização foi encontrado
        if [ -z "$arquivo_versao_atual" ]; then
            ERRO_MSG "Pacote de atualizacao da versao nao encontrado"
            echo "Pacote de atualizacao da versao nao encontrado! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
            return
        else
            ALERTA_MSG "Descompactando a 'versao'... Por favor, aguarde!"
            total_files=$(rar lb "$arquivo_versao_atual" | wc -l)
            current_file=0

            if rar e -o+ "$arquivo_versao_atual" | while read -r line; do
                ((current_file++))
                percent=$((current_file * 100 / total_files))
                echo -ne "Atualizando: [$percent%]\r"
            done
            then
                INFO_MSG "Atualizacao de Versao concluida!"
                versaoLoja="$novoPortal"
                
                rm -rf "$arquivo_versao_atual"
                INFO_MSG "Versao atualizada para '$novoPortal'"
                sleep 1

                # Verifica se o arquivo da release foi encontrado
                if [ -z "$arquivo_release_atual" ]; then
                    ERRO_MSG "Pacote de atualizacao da release nao encontrado"
                    echo "Pacote de atualizacao da release nao encontrado! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
                    return
                else
                    total_files_release=$(rar lb "$arquivo_release_atual" | wc -l)
                    current_file_release=0
                    ALERTA_MSG "Descompactando a 'release'... Por favor, aguarde!"
                    if rar e -o+ "$arquivo_release_atual" | while read -r line; do
                        ((current_file_release++))
                        porcento=$((current_file_release * 100 / total_files_release))
                        echo -ne "Atualizando: [$porcento%]\r"
                    done
                    then
                        INFO_MSG "Atualizacao de Release concluida!"
                        rm -rf "$arquivo_release_atual"
                    else
                        ERRO_MSG "Erro ao atualizar!"
                        echo "Erro ao atualizar INTEGRAL! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
                        exit 1
                    fi
                    echo ""
                    INFO_MSG "Release atualizada"
                    inf_releaseLoja="$letraRelease"
                fi
            else
                ALERTA_MSG "Nova Versao Disponivel, mas nao foi possivel atualizar. Entre em contato com o suporte Avanco!"
                echo "Nova Versao Disponivel, mas nao foi possível atualizar. Entre em contato com o suporte Avanco! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
                exit 1
            fi
        fi
    elif [ "$inf_versaoLoja" == "$novoPortal" ]; then
        if [ "$inf_releaseLoja" != "$letraRelease" ]; then
            if [ -z "$arquivo_release_atual" ]; then
                ERRO_MSG "Pacote de atualizacao da release nao encontrado"
                echo "Pacote de atualizacao da release nao encontrado! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
                return
            else
                ALERTA_MSG "Descompactando a 'release'... Por favor, aguarde!"
                total_files_release=$(rar lb "$arquivo_release_atual" | wc -l)
                current_file_release=0
                if rar e -o+ "$arquivo_release_atual" | while read -r line; do
                    ((current_file_release++))
                    porcento=$((current_file_release * 100 / total_files_release))
                    echo -ne "Atualizando: [$porcento%]\r"
                done
                then
                    INFO_MSG "Atualizacao de Release Concluida!"
                    rm -rf "$arquivo_release_atual"
                    inf_releaseLoja="$letraRelease"
                else
                    ALERTA_MSG "Nova Release Disponivel, mas nao foi possivel atualizar. Entre em contato com o suporte Avanco!"
                    echo "Nova Release Disponivel, mas nao foi possivel atualizar. Entre em contato com o suporte Avanco! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
                    exit 1
                fi
                echo
                INFO_MSG "Atualizacao concluida com sucesso."
            fi
        else
            echo "INTEGRAL JA ESTA COM A RELEASE MAIS RECENTE!"
            echo "INTEGRAL JA ESTA COM A RELEASE MAIS RECENTE! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $LOG_FILE
        fi
    else
        echo "INTEGRAL JA ESTA COM VERSAO E RELEASE MAIS RECENTES!"
        echo "INTEGRAL JA ESTA COM VERSAO E RELEASE MAIS RECENTES! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $LOG_FILE
    fi

    sleep 1
    echo "Aguarde..."
    atu-help manual
    if [ $? -ne 0 ]; then
        ERRO_MSG "Erro ao executar 'atu-help manual'."
        echo "Erro ao executar 'atu-help manual'! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
        exit 1
    fi

    chmod 777 /u/sist/exec/*.gnt || {
        ERRO_MSG "Erro ao conceder permissoes."
        echo "Erro ao conceder permissoes! $(date +"%d/%m/%Y") - $(date +"%H:%M:%S")" >> $ERRO_LOG_FILE
        exit 1
    }

    INFO_MSG "Atualizacao realizada com sucesso!"
    LOG_INFO "Atualizacao realizada com sucesso pela rotina AUTOMATICA!"

    rm "$controle_flag/controle_flag.txt"
}

# Funcao para atualizar o script sempre para a versao mais recente
UPDATE () {
    SCRIPT_PATH="$0"
    TMP_PATH=$(mktemp /tmp/$(basename "$SCRIPT_PATH").XXXXXX)
    echo "Baixando versao mais recente do atualizador"
    if curl --output /dev/null --silent --head --fail "$SCRIPT_URL"; then
        wget -qcO "$TMP_PATH" "$SCRIPT_URL"
    
        if [ $? -eq 0 ]; then
            mv "$TMP_PATH" "$SCRIPT_PATH"
            chmod +x "$SCRIPT_PATH"
            echo "Atualizacao concluida. Execute o script novamente..."
        else
            echo "Erro ao baixar a atualizacao."
            rm -f "$TMP_PATH"
        fi
    else
        echo "ERRO: a URL do atualizador nao esta acessivel."
        rm -f "$TMP_PATH"
    fi
    
    exit
}

# Funcao que gravara a versao e release apos a atualizacao
GRAVANDO_ATUALIZACOES() {
    cobrun status-online.gnt "A" > /dev/null
    inf_versaoLoja="$novoPortal"
    data_configuracao=$(date +'%d/%m/%Y')
    data_exibir=$(TRATAR_DATAS "$inf_versaoLoja")
    data_rel_exibir=$(TRATAR_DATAS "$data_release")
    
    echo "$inf_versaoLoja" > "/u/sist/controle/inf_versaoLoja.txt"
    echo "$inf_releaseLoja" > "/u/sist/controle/inf_releaseLoja.txt"
    

    #clear
    echo
    echo "GRAVANDO INFORMACOES..."
    echo
    echo "VERSAO COBOL: $inf_versaoCobol"
    echo "VERSAO INTEGRAL INSTALADA: $data_exibir"
    echo "RELEASE INTEGRAL INSTALADA: $inf_releaseLoja"
    echo "DATA DA RELEASE INSTALADA: $data_rel_exibir"

    #echo "Gravando informacoes novas informacoes. Por favor, aguarde..."
    # cria arquivo txt que vai ser lido pelo cron e pelo atualizadorAutomatico que ficara em '/u/bats'
    if [ ! -e "$info_loja_txt" ]; then
        touch "$info_loja_txt"
    fi
    
    echo "DATA: $data_configuracao" > "$info_loja_txt"
    echo "VERSAO COBOL: $inf_versaoCobol" >> "$info_loja_txt"
    echo "VERSAO INTEGRAL: $inf_versaoLoja" >> "$info_loja_txt"
    echo "RELEASE: $inf_releaseLoja" >> "$info_loja_txt"
    echo "DATA RELEASE: $data_release" >> "$info_loja_txt"


    echo
    echo "INFORMACOES GRAVADAS COM SUCESSO!"
    echo
    echo "Sistema atualizado em $data_configuracao"
    cronometro_start=$cronometro_start
    cronometro_stop="$(date +'%H:%M:%S')"
    cronometro_stop_volta=$SECONDS
    tempo_gasto=$(( cronometro_stop_volta - cronometro_start_volta ))
    tempo_gasto_formatado=$(date -u -d @${tempo_gasto} +"%M min  e %S seg")
    echo "     $(date +"%d/%m/%y")       -     $cronometro_start     -     $cronometro_stop    -  $tempo_gasto_formatado" >> "/u/sist/logs/infos_extras.log"
    echo "---------------------------------------------------------------------------------" >> "/u/sist/logs/infos_extras.log"
    echo "$AVANCO"
    sleep 2
    exit 0
}

# Funcao para baixar arquivo atualizado
BAIXAR_CONTROLE () {
    echo "ATUALIZANDO INFORMACOES DE VERSAO E RELEASE"
    curl -o "$info_loja_txt.tmp" "$URL_CONTROLE_VERSAO_RELEASE" || wget -ocq "$info_loja_txt.tmp" "$URL_CONTROLE_VERSAO_RELEASE"

    if [ $? -eq 0 ]; then
        mv "$info_loja_txt.tmp" "$arquivo"
        chmod 766 "$info_loja_txt"
        clear
        echo "DETALHES DE VERSAO E RELEASE OBTIDOS!"
    else
        echo "ERRO AO OBTER VERSAO E RELEASE RECENTES!"
        rm -f "$info_loja_txt.tmp"
    fi
}

MENU_SECRETO () {
    clear
    while true; do
        echo " ___________________________________________________________________________"
        echo "|                                                                           |"
        echo "|  1) OBTER INFORMACOES DO SISTEMA         7) CONFIGURAR ROTINA NO CRON     |"
        echo "|  2) ATUALIZAR                            8) OBTER UPDATE DO ATUALIZADOR   |"
        echo "|  3) REVERTER ATUALIZACAO                 9) PARAMETRIZACAO                |"
        echo "|  4) BACKUP EXECUTAVEIS                   10) MANUAL                       |"
        echo "|  5) CORRIGIR FALHAS DE ATUALIZACAO       99) SAIR                         |"
        echo "|  6) VISUALIZAR LOGS                                                       |"
        echo "|___________________________________________________________________________|"
        read -p "ESCOLHA UMA OPCAO: " opcao
        case $opcao in
            1)
                clear
                echo "OBTER INFORMACOES ATUAIS DO INTEGRAL"
                more "/u/sist/controle/info_loja.txt"
                ;;
            2)
                clear
                echo "ATUALIZAR"
                VERIFICA_ATUALIZACAO
                INICIAR
                chmod 777 /u/sist/exec/*.gnt 2>> "$VALIDADOS_GNT"
                LER_ARQUIVO_TEXTO
                LIMPA_EXEC
                SEGURANCA
                ATUALIZAR
                chmod 777 /u/sist/exec/*.gnt 2>> "$VALIDADOS_GNT"
                GRAVANDO_ATUALIZACOES
                ;;
            3)
                clear
                echo "REVERTER ATUALIZACAO"
                menu_restaura
                ;;
            4)
                clear
                echo "BACKUP"
                FAZER_BKP
                ;;
            5)
                clear
                echo "CORRIGIR FALHAS DE ATUALIZACAO"
                echo "$GUIA_ERROS"
                ;;
            6)
                clear
                echo
                ;;
            7)
                clear
                echo "CONFIGURAR ROTINA NO CRON"
                if [ $USER = avanco ]; then
                    echo "LIBERADO PARA CONFIGURAR"
                else
                    echo "Favor acionar o Suporte Avanco para realizar a configuracao"
                    exit
                fi
                ;;
            8)
                clear
                echo "OBTER UPDATE DO ATUALIZADOR"
                UPDATE
                ;;
            9)
                clear
                echo "PARAMETRIZACAO"
                ;;
            10)
                clear
                echo "$MANUAL_USO"
                ;;
            1188)
                clear
                if [ $USER = avanco ]; then
                    echo "LIBERADO PARA CONFIGURAR"
                else
                    echo "Favor acionar o Suporte Avanco para realizar a configuracao"
                    exit
                fi
                echo "MANUAL AVANCO"
                echo ""
                ;;
            "avanco" | "AVANCO")
                clear
                if [ $USER = avanco ]; then
                    echo "LIBERADO PARA CONFIGURAR"
                else
                    echo "Favor acionar o Suporte Avanco para realizar a configuracao"
                    exit
                fi
                echo "menu"
                ;;
            99)
                clear
                tput smso
                echo ""
                echo "                                AVANCO INFORMATICA                              "
                echo ""
                echo "                            TELESUPORTE (31) 3025-1188                          "
                echo ""
                echo "                                    TELEGRAM                                    "
                echo ""
                echo "                            t.me/avancoinformatica_bot                          "
                tput rmso
                stty sane
                sleep 5
                exit 0
                ;;
            *)
                echo "OPCAO INVALIDA! TENTE NOVAMENTE."
                ;;
        esac
        read -p "PRESSIONE QUALQUER TECLA PARA CONTINUAR... " -n 1
        clear
    done
}

# funcao para controlar a restauracao.
menu_restaura () {
    echo "criar menu com opcoes"
}


# Funcao para extrair e exibir a versao do programa
mostrar_versao() {
    local versao=$(grep '^# DATA:' "$0" | head -1 | cut -d '-' -f 2 | sed 's/Versao //')
    echo -n "-Programa: $(basename "$0")"
    echo
    echo "-Versao:  $versao"
}




###############################
# Tratamento das opcoes que serao responsaveis por controlar na linha de comando
# ------------------------------------------------------------------------------

case "$1" in
-h | --help)
    clear
    echo "$MANUAL_USO"
    exit 0
    ;;
-V | -v | --version)
    # Extrai a versao diretamente do cabecalho do programa
    mostrar_versao
    exit 0
    ;;
-i | --info)
    clear
    echo "OBTER INFORMACOES DO ATUAIS DO INTEGRAL"
    more "/u/sist/controle/info_loja.txt"
    exit 0
    ;;
-d | --download)
    BAIXAR_ATUALIZACOES
    exit 0
    ;;
-b | --backup)
    FAZER_BKP
    VERIFICA_BACKUP
    exit 0
    ;;
-m | --menu)
    MENU_SECRETO
    exit 0
    ;;
-up | --update)
    # criar rotina pra baixar nova versao do atualizador.
    echo "Buscando update para o Atualizador..."
    UPDATE
    exit 0
    ;;
--man)
    man atualizador
    exit 0
    ;;
-o | --obter)
    # Busca no servidor a versao e release atualizada e exibi no terminal
    BAIXAR_CONTROLE
    bash "$script_baixar_atualizacao" "-o"
    exit 0
    ;;
-r | --restore)
    echo "criar opcao de restaurar"
    exit 0
    ;;
-l | --log)
    echo "criar chamada do ultimo log"
    exit 0
    ;;
--config)
    echo "criar opcao de configurar parametros"
    exit 0
    ;;
--alterar)
    echo "criar opcao para alterar os parametros configurados"
    exit 0
    ;;
--list)
    echo "criar opcao de listar configuracao"
    exit 0
    ;;
--cron)
    echo "criar opcao de adicionar no cron"
    exit 0
    ;;
*)
    if test -n "$1"; then
        echo Opcao invalida: $1
        exit 1
    fi
    ;;
esac

###############################

# Chamandos as funcoes na ordem

verificar_dia
checar_internet
VERIFICA_ATUALIZACAO
INICIAR
chmod 777 /u/sist/exec/*.gnt 2>> "$VALIDADOS_GNT"
LIMPA_EXEC
LER_ARQUIVO_TEXTO
SEGURANCA
LER_ARQUIVO_TEXTO
ATUALIZAR
chmod 777 /u/sist/exec/*.gnt 2>> "$VALIDADOS_GNT"
GRAVANDO_ATUALIZACOES
UPDATE > /dev/null
