#!/bin/bash
#
################################################################################
# baixarAtualizacao - Ira ler o arquivo gerado e baixar a atualizacao referente a data
#
# DATA: 01/07/2024 20:48 - Versao 1
#
# ------------------------------------------------------------------------------
# Autor: Luiz Gustavo <luiz.gustavo@avancoinfo.com.br>
#                     <luizgcesar@gmail.com.br>
# site: https://github.com/ketteiGustavo
# ------------------------------------------------------------------------------
# Versao 1: leitura do arquivo que contem a informacao
# ------------------------------------------------------------------------------
# Objetivo: facilitar a execucao do atualizador.
###############################


MENSAGEM_USO="
Programa: $(basename "$0")

--------------------------------------------------------------------------------
                              [OPCOES DISPONIVEIS]

OPCOES NA LINHA DE COMANDO:
    -h, --help      Mostra esta tela de ajuda e sai
    -V, --version   Mostra a versao do programa e sai
MODO DE USAR:

--------------------------------------------------------------------------------
"
#

# variaveis
URL_BASE_VERSAO40="https://s3.amazonaws.com/avancoprogramas/integral/versao40-"
URL_BASE_VERSAO41="https://s3.amazonaws.com/avancoprogramas/integral/versao41-"

URL_BASE_RELEASE40="https://s3.amazonaws.com/avancoprogramas/integral/release40-"
URL_BASE_RELEASE41="https://s3.amazonaws.com/avancoprogramas/integral/release41-"

URL_ATUALIZADOV40=""
URL_ATUALIZADOV41=""

URL_ATUALIZADO_RELEASE=""

URL_ATUALIZADO_RELEASE_V40=""
URL_ATUALIZADO_RELEASE_V41=""

URL_BUSCAR_RELEASE=""

versao_Portal=""
release=""
data_release=""
cobolBusca=""

release_busca=""

PASTA_DESTINO="/u/rede/avanco/atualizacoes"

infos_extras="/u/sist/logs/infos_extras.log"

SCRIPT_PATH="$0"
SCRIPT_URL="https://raw.githubusercontent.com/ketteiGustavo/atualizador/main/Atual/baixarAtualizacao"
URL_CONTROLE_VERSAO_RELEASE="https://raw.githubusercontent.com/ketteiGustavo/atualizador/main/Atual/controle_ver_rel.txt"

data_atual=$(date +%Y%m%d)
#data_atual="20240718"

atualizado_flag=""
controle_flag="/u/sist/controle"





sleep 1
clear
# Funcao para extrair e exibir a versao do programa
mostrar_versao() {
    local versao=$(grep '^# DATA:' "$0" | head -1 | cut -d '-' -f 2 | sed 's/Versao //')
    echo -n "-Programa: $(basename "$0")"
    echo
    echo "-Versao: $versao"
}



arquivo="/u/sist/controle/controle_ver_rel.txt"

# Funcao para verificar qual o cobol usado
VERIFICA_COBOL() {
    RESULTADO=$(cobrun 2>&1)
    if [[ $RESULTADO =~ V([0-9]+\.[0-9]+) ]]; then
        versaoCobol="${BASH_REMATCH[1]}"
        echo "Versao do Cobol: $versaoCobol"
        inf_versaoCobol="$versaoCobol"
    fi
    #versaoCobol="4.0"
}

# Funcao para tratar datas e inserir barras entre os digitos deixando DD/MM/AA
TRATAR_DATAS () {
    entrada_data=$1
    dia_td=${entrada_data:0:2}
    mes_td=${entrada_data:2:2}
    ano_td=${entrada_data:4:2}
    data_tratada="${dia_td}/${mes_td}/${ano_td}"
    echo "$data_tratada"
}


# Função para ler o arquivo e armazenar as informações em variáveis
ler_arquivo() {
    local arquivo="/u/sist/controle/controle_ver_rel.txt"
    local versao
    local lendo_atualizado
    declare -A releases

    while IFS= read -r linha; do
        if [[ "$linha" =~ ^Informacoes\ atualizadas\ em:\ ([0-9]+)$ ]]; then
            lendo_atualizado="${BASH_REMATCH[1]}"
        elif [[ "$linha" =~ ^Versao\ disponivel\ no\ portal:\ ([0-9]+)$ ]]; then
            versao="${BASH_REMATCH[1]}"
        elif [[ "$linha" =~ ^RELEASE\ ([A-Z])\ -\ DATA:\ ([0-9]+)$ ]]; then
            releases["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
        fi
    done < "$arquivo"

    data_atualizada=$(TRATAR_DATAS "$lendo_atualizado")
    echo ""
    echo "INFORMACOES ATUALIZADAS EM: $data_atualizada"
    echo ""
    data_exibicao=$(TRATAR_DATAS "$versao")
    echo "VERSAO DISPONIVEL NO PORTAL: $data_exibicao"
    versao_Portal="$versao"
    
    echo "$versao" > "/u/sist/controle/versaoIntegral"
    for release in "${!releases[@]}"; do
        
        echo "RELEASE $release - DATA: ${releases[$release]}" > /dev/null
    done
    
    # Verificar a release disponível de acordo com a data atual
    verificar_release_disponivel "$versao" releases
}

# Função para converter data no formato DDMMYY para YYYY-MM-DD
converter_data() {
    local data="$1"
    echo "20${data:4:2}-${data:2:2}-${data:0:2}"
}

# Função para verificar a release disponível de acordo com a data atual
verificar_release_disponivel() {
    local versao="$1"
    declare -n releases_ref="$2"

    #echo "mostrando data de hoje: $data_atual"

    for release in "${!releases_ref[@]}"; do
        local data_release="${releases_ref[$release]}"
        local data_release_yyyymmdd=$(date -d "$(converter_data "$data_release")" +%Y%m%d)

        if [[ "$data_atual" -ge "$data_release_yyyymmdd" ]]; then
            release_formatada=$(TRATAR_DATAS "$data_release")
            echo "RELEASE DISPONIVEL NO PORTAL: $release - DATA: $release_formatada"
            echo "$release" > "/u/sist/controle/releaseIntegral"
            echo "$data_release" > "/u/sist/controle/dataReleaseIntegral"
            return
        fi
    done

    echo "RELEASE ESTARA DISPONIVEL NOS PROXIMOS DIAS!"
}

# Funcao para converter datas no formato YYYYMMDD, para ser usado em equacoes de comparacao, maior, menor e igual
CONVERTER_DATAS() {
    local dia="${1:0:2}"
    local mes="${1:2:2}"
    local ano="${1:4:2}"
    
    #echo "Dia: $dia"
    #echo "Mes: $mes"
    #echo "Ano: $ano"
    
    # Convertendo para o formato 'YYYYMMDD' para facilitar a adição de dias
    local data_formatada="20${ano}${mes}${dia}"
    echo "$data_formatada"
    
}

# Funcao para obter o link da versao atual, com base em comparacao de data por trimestre
BAIXAR_VERSAO() {
    VERIFICA_COBOL
    versaoBusca=$(cat "/u/sist/controle/versaoIntegral")
    #echo "$versaoBusca"
    # Verificando a versao do COBOL
    if [ "$versaoCobol" == "4.0" ]; then
        URL_BUSCAR_VERSAO="$URL_BASE_VERSAO40"
        cobolBusca="40"
    elif [ "$versaoCobol" == "4.1" ]; then
        URL_BUSCAR_VERSAO="$URL_BASE_VERSAO41"
        cobolBusca="41"
    else
        echo "Versao do COBOL invalida."
        echo "Versao do COBOL invalida." >> $ERRO_LOG_FILE
        exit 1
    fi

    URL_ATUALIZADO="$URL_BUSCAR_VERSAO$versaoBusca.rar"
    if curl --output /dev/null --silent --head --fail "$URL_ATUALIZADO"; then
        wget -c --progress=dot "$URL_ATUALIZADO" -P "$PASTA_DESTINO" 2>&1 | \
        grep --line-buffered "%" | \
        sed -u -e "s,\.,,g" | \
        awk '{ printf("\rSTATUS DOWNLOAD: %s CONCLUIDO", $2) }'
        echo ""
        sleep 1
        arquivo_versao_atual=$(find "$PASTA_DESTINO" -type f -name "versao$cobolBusca-$versaoBusca.rar")
        testar_arquivos_versao=$(rar t "$arquivo_versao_atual" | wc -l)
        arquivo_atual_testando=0
        if rar t $arquivo_versao_atual | while read -r line; do
            ((arquivo_atual_testando++))
            porcentagem=$((arquivo_atual_testando * 100 / testar_arquivos_versao))
            echo -ne "TESTANDO INTEGRIDADE DOS .gnt: [$porcentagem%]\r"
        done
        then
            versao_exibir=$(TRATAR_DATAS "$versaoBusca")
            echo "DOWNLOAD DA VERSAO '$versao_exibir' CONCLUIDO E PROGRAMAS 'TESTADOS'!"
        else
            echo "ARQUIVO CORROMPIDO!"
            echo "ARQUIVO DA VERSAO $versaoBusca CORROMPIDO!"
        fi
        return 0
    fi
    sleep 1
}

# Funcao para verificar se a release e valida e mais recente
BAIXAR_RELEASE() {
    VERIFICA_COBOL
    arquivo_release_atual=""
    buscarV40="release40"
    buscarV41="release41"
    releaseBusca=""

    if [ -f "/u/sist/controle/dataReleaseIntegral" ] && [ -s "/u/sist/controle/dataReleaseIntegral" ]; then
        release_busca=$(cat "/u/sist/controle/dataReleaseIntegral")
    else
        release_busca=""
    fi
    if [ -f "/u/sist/controle/versaoIntegral" ] && [ -s "/u/sist/controle/versaoIntegral" ]; then
        versao_busca=$(cat "/u/sist/controle/versaoIntegral")
    fi

    #echo "arquivo txt release: $release_busca"
    #echo "arquivo txt versao : $versao_busca"
    local rel="${release_busca:0:4}"
    local ver="${versao_busca:0:4}"
    
    #echo "tratada versao: $ver"
    #echo "tratada release: $rel"
    

    # Verificando a versao do COBOL
    if [ "$versaoCobol" == "4.0" ]; then
        URL_BUSCAR_RELEASE="$URL_BASE_RELEASE40"
        cobolBusca="40"
        releaseBusca=$buscarV40
    elif [ "$versaoCobol" == "4.1" ]; then
        URL_BUSCAR_RELEASE="$URL_BASE_RELEASE41"
        cobolBusca="41"
        releaseBusca=$buscarV41
    else
        echo "VERSAO DO COBOL INVALIDA."
        exit 1
    fi

    URL_ATUALIZADO_RELEASE="$URL_BUSCAR_RELEASE$ver-a-$rel.rar"
    if curl --output /dev/null --silent --head --fail "$URL_ATUALIZADO_RELEASE"; then
        wget -c --progress=dot "$URL_ATUALIZADO_RELEASE" -P "$PASTA_DESTINO" 2>&1 | \
        grep --line-buffered "%" | \
        sed -u -e "s,\.,,g" | \
        awk '{ printf("\rSTATUS DOWNLOAD: %s CONCLUIDO", $2) }'
        echo ""

        arquivo_release_atual=$(find "$PASTA_DESTINO" -type f -name "$releaseBusca-$ver-a-$rel.rar")
        sleep 1

        testar_arquivos_release=$(rar t "$arquivo_release_atual" | wc -l)
        release_release_testando=0
        if rar t $arquivo_release_atual | while read -r line; do
            ((release_atual_testando++))
            porcentagem=$((arquivo_release_testando * 100 / testar_arquivos_release))
            echo -ne "TESTANDO INTEGRIDADE DOS .gnt: [$porcentagem%]\r"
        done
        then
            release_download=$(TRATAR_DATAS "$release_busca")
            echo "DOWNLOAD DA RELEASE '$letra_release_atual, DO DIA $release_download' CONCLUIDO E PROGRAMAS 'TESTADOS'!!"
        else
            echo "Arquivo corrompido!"
            echo "Arquivo de release '$release_download - $letra_release_atual' corrompido!"
        fi

        echo "PACOTE DE ATUALIZACAO BAIXADO!"
        return 0
    fi
    sleep 1
}

# Funcao para validar versao e release no cliente e baixar somente o necessario
VALIDAR_VERSAO_RELEASE () {
    atualizado_flag=false
    local data_versao_comparar=$(CONVERTER_DATAS "$versao_Portal")
    local letra_release_atual="$release"
    local calculo_data=$(date -d "${data_versao_comparar} +6 days" +"%Y%m%d")
    local calculo_data_limite=$(date -d "${data_versao_comparar} +3 months" +"%Y%m%d")
    #echo "1: $calculo_data"
    #echo "2: $calculo_data_limite"
    #echo "3: $data_versao_comparar"

    versao_informada=$(cat "/u/sist/controle/inf_versaoLoja.txt") 2> /dev/null
    letra_informada=$(cat "/u/sist/controle/inf_releaseLoja.txt") 2> /dev/null

    #read -p "LER VERSAO: " versao_informada

    local data_informada_comparar=$(CONVERTER_DATAS "$versao_informada")
    #echo "$data_informada_comparar"
    if [ "$data_informada_comparar" -gt "$calculo_data" ] && [ $data_informada_comparar -lt $calculo_data_limite ]; then
        echo "A RELEASE ATUAL E: $letra_release_atual" > /dev/null
    fi
    #read -p "LER RELEASE: " letra_informada
    letra_informada=$(echo "$letra_informada" | tr '[:lower:]' '[:upper:]')

    #echo "voce informou: $letra_informada"
    if [[ "$letra_informada" > "M" ]]; then
        echo "RELEASE INVALIDA"
    fi

    if [ "$data_informada_comparar" -lt "$data_versao_comparar" ]; then
        echo "INICIANDO DOWNLOAD..."
        BAIXAR_VERSAO
        BAIXAR_RELEASE
        atualizado_flag=false
        echo "$atualizado_flag" > $controle_flag/controle_flag.txt
    elif [ "$data_informada_comparar" -eq "$data_versao_comparar" ]; then
        echo "INTEGRAL ESTA COM A VERSAO ATUAL!"
        atualizado_flag=true
        echo "$atualizado_flag" > $controle_flag/controle_flag.txt
        #echo "$data_atual"
        if [ "$data_atual" -gt "$calculo_data" ]; then
            echo "A RELEASE ATUAL E: $letra_release_atual" > /dev/null
            if [[ "$letra_informada" < "$letra_release_atual" ]]; then
                echo "BAIXANDO RELEASE..."
                BAIXAR_RELEASE
                atualizado_flag=false
                echo "$atualizado_flag" > $controle_flag/controle_flag.txt
            elif [[ "$letra_informada" == "$letra_release_atual" ]]; then
                echo "INTEGRAL ESTA COM A RELEASE ATUAL!"
                atualizado_flag=true
                echo "$atualizado_flag" > $controle_flag/controle_flag.txt
            else
                echo "RELEASE INVALIDA!"
            fi
        
        fi


            
    else
        echo "VERSAO INVALIDA!"
    fi

    echo "status flag: $atualizado_flag" > /dev/null
    echo "$atualizado_flag" > $controle_flag/controle_flag.txt
}

# Funcao para atualizar o script sempre para a versao mais recente
UPDATE () {
    SCRIPT_PATH="$0"
    TMP_PATH_D=$(mktemp /tmp/$(basename "$SCRIPT_PATH").XXXXXX)
    echo "Baixando versao mais recente do atualizador"
    if curl --output /dev/null --silent --head --fail "$SCRIPT_URL"; then
        wget -qcO "$TMP_PATH_D" "$SCRIPT_URL"
    
        if [ $? -eq 0 ]; then
            mv "$TMP_PATH_D.tmp" "$SCRIPT_PATH"
            chmod +x "$TMP_PATH_D"
            echo "Atualizacao concluida. Execute o script novamente..."
        else
            echo "Erro ao baixar a atualizacao."
            rm -f "$TMP_PATH_D"
        fi
    else
        echo "ERRO: a URL do atualizador nao esta acessivel."
        rm -f "$TMP_PATH_D"
    fi
}


# Funcao para baixar arquivo atualizado
BAIXAR_CONTROLE () {
    echo "OBTENDO VERSAO E RELEASE"
    curl -o "$arquivo.tmp" "$URL_CONTROLE_VERSAO_RELEASE" || wget -ocq "$arquivo.tmp" "$URL_CONTROLE_VERSAO_RELEASE"

    if [ $? -eq 0 ]; then
        mv "$arquivo.tmp" "$arquivo"
        chmod 766 "$arquivo"
        clear
        echo "DETALHES DE VERSAO E RELEASE OBTIDOS!"
    else
        echo "ERRO AO OBTER VERSAO E RELEASE RECENTES!"
        rm -f "$arquivo.tmp"
    fi
}



###############################
# Tratamento das opcoes que serao responsaveis por controlar na linha de comando
# ------------------------------------------------------------------------------

case "$1" in
-h | --help)
    clear
    echo "$MENSAGEM_USO"
    exit 0
    ;;
-V | --version)
    # Extrai a versao diretamente do cabecalho do programa
    clear
    mostrar_versao
    exit 0
    ;;
-up | --update)
    clear
    UPDATE
    exit 0
    ;;
-o | --obter)
    clear
    BAIXAR_CONTROLE
    ler_arquivo
    exit 0
    ;;
*)
    if test -n "$1"; then
        echo Opcao invalida: $1
        exit 1
    fi
    ;;
esac

###############################


# Chamar a função com o caminho do arquivo
clear
BAIXAR_CONTROLE
ler_arquivo
VALIDAR_VERSAO_RELEASE
UPDATE > /dev/null
